# platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'SwapProfit' do
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"

  pod 'Stripe', '~> 19.0.1'

  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'SwapProfitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  
end

target 'SwapProfit-tvOS' do
  # Pods for SwapProfit-tvOS

  target 'SwapProfit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

use_flipper!
post_install do |installer|
  flipper_post_install(installer)
end